export function createCompanyProfile({
  id,
  name,
  cnpj,
  location,
  state,
  serviceAreas,
  productCategories,
  productCategoriesStatus,
  minimumDesiredMargin,
  financialCapacity,
  logisticsCapacity,
  stockCapacity,
  suppliers,
  documentation,
  observations,
}) {
  return {
    id,
    name,
    cnpj,
    location,
    state,
    serviceAreas,
    productCategories,
    productCategoriesStatus,
    minimumDesiredMargin,
    financialCapacity,
    logisticsCapacity,
    stockCapacity,
    suppliers,
    documentation,
    observations,
  }
}
